### PR TITLE
Improve the overall UI of the app

### LINKED ISSUE #1: Improve Website UI
- [ ] Add icons to the respective tools 
- [ ] Add hover effect on all the tools
- [ ] Improve the over all UI

### LINKED ISSUE #2: Make website responsive
Ask to be assigned the issue

### LINKED ISSUE #3: Change cursor w.r.t it's functionality
Ask to be assigned the issue
Change the cursor w.r.t the tool used, a brush while using the brush tool, easer for eraser tool, a pencil for the different shapes used, fill bucket for color selector.

### LINKED ISSUE #5: Create new empty color boxes
Ask to be assigned the issue
Add 4 more empty color boxes under the existing boxes

### LINKED ISSUE #6: Store and display the selected color from color picker
Ask to be assigned
- [ ] New color can be assigned to the empty box when selected from the color picker

### LINKED ISSUE #8: Make Clear Canvas button working

### LINKED ISSUE #17: bug: erased area in the canvas becomes white when the image is saved
The saved file is `png` and it is clearly shown that the eraser made the erased area white. So when the image is saved, it shows white color.

**canvas**

image

**saved `draw.png`**

draw

### PR DESCRIPTION
**Pull request by chankruze**
**DONE:**
- [x] add top action bar that contains all the tools and action buttons
- [x] canvas readback optimization
- [x] add pencil tool
- [x] fixes #1
- [x] fixes #2
- [x] fixes #3
- [x] fixes #5
- [x] fixes #6
- [x] fixes #8
- [x] fixes #17

TODO:
- [ ] improve canvas resizing w.r.t. window.

### CODE REVIEW

**Comment by chankruze** [comment]
@OindrilaDas27 all conflicts are resolved.

**Comment by chankruze** [comment]
@OindrilaDas27 conflicts are resolved and waiting for review.

**Comment by OindrilaDas27** [comment]
Good Work!

**Comment by chankruze** [comment]
Thanks!

**Pull request merged**
